### ISSUE TITLE
有个问题想请教一下

### ISSUE THREAD

**Issue by chenyihong518** [KenyeeC/eleFixed#3]
您好，如果表格高度固定，表格内容滚动，您的插件要怎么在这种情况下固定表头？我使用的时候，只有在页面滚动的时候才能表头固定。

**Comment by KenyeeC** [comment]
你好，感谢你使用eleFixed！但是很遗憾地告诉你，eleFixed并不能在页面不滚动的情况下固定某个元素，因为eleFixed是通过window的onscroll事件来判断是否固定元素的
