### ISSUE TITLE
表头没有遮住 tbody

### ISSUE THREAD

**Issue by arnbunchen** [KenyeeC/eleFixed#4]
表头没有遮住 tbody,而是在下面。
![image](https://user-images.githubusercontent.com/1029500/39341024-d624481c-4a03-11e8-85d0-c4ad566bcaa1.png)

**Comment by KenyeeC** [comment]
想看看你的table结构和样式是怎么样的，尤其是thead的样式

**Comment by KenyeeC** [comment]
长期没有收到反馈，此 issue 关闭
