### ISSUE TITLE
请教实现表头上方添加一button后，button和表头均固定

### ISSUE THREAD

**Issue by Yong2020** [KenyeeC/eleFixed#9]
你好，多谢你的code，我在本地使用chrome已经test成功，赞一个！

我想在表格上方添加一个button，然后上拉页面时，button和表头相对位置不发生变化，且均固定在页面顶部，请问如何实现？

如果赐教，不胜感激~

**Comment by KenyeeC** [comment]
一个比较投机取巧的方法看看行不行，在 thead 前加个伪类去做按钮，然后固定的还是 thead 就好了..
